name: build

[![build](https://github.com/paypal/paypal-sdk-release/actions/workflows/main.yml/badge.svg?branch=main)](https://github.com/paypal/paypal-sdk-release/actions/workflows/main.yml)

on:
  # run on push but only for the main branch
  push:
    branches:
      - main
  # run for every pull request
  pull_request: {}
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v2

      - name: ⎔ Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: 📥 Download deps
        uses: bahmutov/npm-install@v1
        with:
          useLockFile: false

      - name: ▶️ Run flow-typed script
        run: npm run flow-typed

      - name: ▶️ Run tests
        run: npm test
