name: publish to npm
on:
  # manually run this action using the GitHub UI
  # https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/
  workflow_dispatch:
    inputs:
      version:
        description: Optional argument for "npm run release"
        required: false
        default: 'patch'
jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14]
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: ⎔ Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: 📥 Download deps
        run: npm run reinstall

      - name: Configure git user
        run: |
          git config --global user.email ${{ github.actor }}@users.noreply.github.com
          git config --global user.name ${{ github.actor }}

      - name: Publish to npm
        run: |
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
            npm run release -- ${{ github.event.inputs.version }}
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
